cloudentity/openbanking-quickstart

data/imports/bank-admins.tmpl
data/imports/bank-customers.tmpl
data/imports/financroo.tmpl
data/imports/openbanking.tmpl
data/variables.yaml
docker-compose.yaml

- Move urls to a variables file

Move urls to a variables file

---

apps/configuration/Dockerfile
docker-compose.yaml

- ship configuration app with embedded imports

ship configuration app with embedded imports

---

.env
docker-compose.yaml

- move import configuration app params to .env file

move import configuration app params to .env file

---

data/imports/openbanking.tmpl
data/imports/system.tmpl
data/variables.yaml

- Move mtls subject dn to variables file

Move mtls subject dn to variables file

---

apps/bank/handler.go
go.mod
go.sum

Reenable and fix risk validation on payment creation

AUT-2587 fix risk validation

---

.env
.github/workflows/cypress-branch.yml
Makefile
docker-compose.yaml
scripts/override_env.sh
scripts/set-mfa.sh
tests/cypress/integration/ConsentAdminTests.ts
tests/cypress/integration/ConsentSelfServiceTests.ts
tests/cypress/integration/FinancrooAccountsTests.ts
tests/cypress/integration/FinancrooPaymentsTests.ts
tests/cypress/integration/TppTechnicalTests.ts
tests/cypress/pages/EnvironmentVariables.ts
tests/cypress/plugins/index.js
tests/package.json

- move enable mfa env to .env
- use dotenv to read .env file for cypress tests
- update github action for cypress
- override env script

Move enable mfa env to .env

---

.env

- Bump acp to a stable version

Bump acp to a stable version

---

.env
docker-compose.yaml

Configurable version

---

.github/workflows/docker-publish.yml
Makefile
README.md
scripts/override_env.sh
scripts/version.sh

Release utils

---

.env
consent/consent-page/templates/base/mfa-verify.tmpl
data/imports/openbanking-br.tmpl
data/variables.yaml
docker-compose.yaml

**[AUT-3344](https://cloudentity.atlassian.net/browse/AUT-3344?atlOrigin=eyJpIjoiOWNkY2JjNzc2ZmU1NDA3OTk5OTZlMWYzMzBkODI3NGIiLCJwIjoiamlyYS1zbGFjay1pbnQifQ
)**
- comment out styles override
- fix MFA tmpl
- add OBBR import

[AUT-3344] Fix MFA template

---

apps/financroo-tpp/web/app/src/components/investments/ContributionCard.tsx
apps/financroo-tpp/web/app/src/components/investments/InvestmentsContributeSuccess.tsx
consent/self-service-portal/web/app/src/components/applicationDetails/ApplicationAccessPaymentDrawer.tsx
tests/cypress/integration/ConsentSelfServiceTests.ts
tests/cypress/integration/FinancrooPaymentsTests.ts
tests/cypress/integration/TppTechnicalTests.ts
tests/cypress/pages/consent-self-service/ConsentSelfServiceApplicationPage.ts
tests/cypress/pages/financroo/investments/FinancrooContributePage.ts

Added  test scenario to cover path with rejecting account payment consent.
Additionally:
- removed waits from FinancrooContributePage
- randomized amount values in tests: FinancrooPaymentsTests and ConsentSelfServiceTests
- added assertions for new amounts

Feature/aut 3432 cypress reject account  payment consent test

---

.env
.env-local
.env-saas
README.md
apps/financroo-tpp/config.go
apps/financroo-tpp/config_test.go
data/imports/admin.tmpl
docker-compose.brasil.yaml
docker-compose.yaml
scripts/go/clean_saas.go

This PR automates the configuration of the quickstart cleanup client to prevent manual entering of the client id and client secret into the .env-saas file. Also, the configuration for .env-saas was simplified.

Saas Integration Improvements and Fixes

---

docker-compose.yaml

Enable CIBA feature flag

---

README.md
docker-compose.yaml

Enable audit events UI in ACP

---

consent/admin-portal/consent_api.go
consent/admin-portal/consent_logic.go
consent/admin-portal/consents_model.go
consent/admin-portal/handler.go
consent/admin-portal/main.go
consent/admin-portal/ob_cdr_logic.go
consent/admin-portal/ob_uk_logic.go
consent/admin-portal/web/app/src/api/api.tsx
consent/admin-portal/web/app/src/components/AccountView/AccountClientCard.tsx
consent/admin-portal/web/app/src/components/AccountView/AccountView.tsx
consent/admin-portal/web/app/src/components/AccountView/AccountViewDetails.tsx
consent/admin-portal/web/app/src/components/AccountView/ConsentTable.tsx
consent/admin-portal/web/app/src/components/AccountView/ConsentTabs.tsx
consent/admin-portal/web/app/src/components/AccountView/Drawers/AccountAccessDrawer.tsx
consent/admin-portal/web/app/src/components/ClientCard.tsx
consent/admin-portal/web/app/src/components/ConsentManagementView/ConsentManagementView.tsx
consent/admin-portal/web/app/src/components/ThirdPartyProvidersView/ThirdPartyProvidersView.tsx
consent/admin-portal/web/app/src/components/utils.tsx
docker-compose.yaml
tests/cypress/integration/cdr/ConsentAdminCDRTests.ts

This PR adds CDR to admin portal.

Feature/aut 4149 add CDR to admin portal

---

consent/admin-portal/web/app/src/components/utils.tsx

This PR fixed a bug where a blank screen is shown in Admin Application when clicking on CDR account access row.

permissions details on cdr admin portal now shown

---

apps/financroo-tpp/web/app/src/components/AccountsAddedDialog.tsx
tests/cypress/integration/obuk/ConsentSelfServiceTests.ts
tests/cypress/integration/obuk/FinancrooPaymentsTests.ts
tests/cypress/pages/financroo/accounts/FinancrooModalPage.ts

Test are randomly failing due to fail to connects to Financroo bank after submitting an access to account.
Fixes:
- Added assertion for FinancrooModalPage - after submitting an access to account
- Added interceptAccountsRequest function to FinancrooModalPage assertion

Added assertion for FinancrooModalPage.

---

.env
.env-local
docker-compose.cdr.yaml
docker-compose.yaml

Bump acp and data recipient apps to include fix for exchanging authorization code using mtls token endpoint alias.
Fix cdr import

Bump acp and data recipient apps

---

Makefile

Add purge images target

---

data/imports/bank-customers.tmpl
data/imports/cdr.tmpl
data/imports/openbanking-br.tmpl
data/imports/openbanking-uk.tmpl

Switch subject format to legacy to work with new workspaces created on SaaS

Use legacy subject format

---

consent/consent-page/mfa_handler.go

Fix mfa consent handler for FDX

Fix mfa consent handler for FDX

---

Jenkinsfile
Makefile
apps/developer-tpp/templates/fdx/fdx-authenticated.tmpl
apps/developer-tpp/templates/fdx/fdx-intent_registered.tmpl
apps/developer-tpp/templates/fdx/fdx-login.tmpl
tests/cypress/integration/fdx/FdxTppConsentTests.ts
tests/cypress/pages/fdx-tpp/FdxTppAuthenticatedPage.ts
tests/cypress/pages/fdx-tpp/FdxTppIntentRegisteredPage.ts
tests/cypress/pages/fdx-tpp/FdxTppLoginPage.ts

- Add new Cypress test to verify FDX implementation - set up locally make `run-fdx-locally`.
- Add new stage **FDX test** to Jenkins pipeline.

Feature/aut 5791 add cypress test for fdx locally [WIP]

---

consent/consent-page/fdx_accounts_mfa_provider.go
consent/consent-page/main.go

Fix FDX flow with MFA enabled

---

apps/financroo-tpp/web/app/src/App.tsx
apps/financroo-tpp/web/app/src/components/AuthPage.jsx
apps/financroo-tpp/web/app/src/components/banks.tsx
apps/financroo-tpp/web/app/src/components/investments/Field.tsx
apps/financroo-tpp/web/app/src/components/investments/InvestmentsContribute.tsx
apps/financroo-tpp/web/app/src/components/investments/InvestmentsContributeMethod.tsx
apps/financroo-tpp/web/app/src/components/investments/InvestmentsContributeSuccess.tsx
apps/financroo-tpp/web/app/src/components/investments/InvestmentsContributeSummary.tsx
apps/financroo-tpp/web/app/src/theme.ts
consent/admin-portal/web/app/package.json
consent/admin-portal/web/app/src/components/AccountView/AccountClientCard.tsx
consent/admin-portal/web/app/src/components/AccountView/AccountView.tsx
consent/admin-portal/web/app/src/components/AccountView/AccountViewDetails.tsx
consent/admin-portal/web/app/src/components/AccountView/ConsentTable.tsx
consent/admin-portal/web/app/src/components/AccountView/Drawers/AccountAccessDrawer.tsx
consent/admin-portal/web/app/src/components/ClientCard.tsx
consent/admin-portal/web/app/src/components/ClientsList.tsx
consent/admin-portal/web/app/src/components/PageToolbar.tsx
consent/admin-portal/web/app/src/components/PrivateRoute.jsx
consent/admin-portal/web/app/src/components/Subheader.tsx
consent/admin-portal/web/app/src/components/ThirdPartyProvidersView/RevokeDrawer.tsx
consent/admin-portal/web/app/src/components/utils.tsx
consent/admin-portal/web/app/src/theme.ts
consent/admin-portal/web/app/yarn.lock

- client status from account_access consent
- fix for theme + uncomment styles
- prettier

AUT-5641 fix client status after revoke

---

docker-compose.acp.local.yaml
docker-compose.cdr.yaml

Update mock-data-recipient version. 
The actual fix was developed here: https://github.com/cloudentity/mock-data-recipient/pull/2

fix consumer data sharing page

---

Jenkinsfile
tests/cypress/integration/cdr/ConsentAdminCDRTests.ts
tests/cypress/integration/cdr/ConsentSelfServiceCDRTests.ts
tests/cypress/integration/fdx/FdxTppConsentTests.ts
tests/cypress/integration/obbr/ConsentAdminTests.ts
tests/cypress/integration/obbr/ConsentSelfServiceTests.ts
tests/cypress/integration/obbr/FinancrooPaymentsTests.ts
tests/cypress/integration/obbr/TppTechnicalTests.ts
tests/cypress/integration/obuk/ConsentAdminTests.ts
tests/cypress/integration/obuk/ConsentSelfServiceTests.ts
tests/cypress/integration/obuk/FinancrooAccountsTests.ts
tests/cypress/integration/obuk/FinancrooPaymentsTests.ts
tests/cypress/integration/obuk/TppTechnicalTests.ts
tests/cypress/integration/saas/obbr/SmokeConsentAdminTests.ts
tests/cypress/integration/saas/obbr/SmokeTppTechnicalTests.ts
tests/cypress/integration/saas/obuk/SmokeConsentAdminTests.ts
tests/cypress/integration/saas/obuk/SmokeTppTechnicalTests.ts
tests/cypress/pages/consent/ConsentPage.ts

- Restore commented Cypress tests for all available specification.
- Restore removed `OBBR Tests with enabled MFA` stage in Jenkinsfile.
-  Add agent cleanup as a part of `post` section in Jenkinsfile to avoid error when the same agent was reused in next build iteration.
```
post { 
cleanup {
script {
if (getContext(hudson.FilePath)) {
deleteDir()
}
}
}
}
```

AUT-5834 Restore commented Cypress tests

---

Jenkinsfile

The master branch should be run, at least once per day.  This is due to the fact that some of the tests are executed on SaaS prod tenant.
Added a crone trigger to run master branch 1 a day between 5:00am - 5:59am (UTC)

AUT-5999 add trigger to run master branch every day

---

Jenkinsfile
Makefile

Run run tests verify in prepare stage

Run run tests verify in prepare stage

---

build/runner.dockerfile

Updated `golangci-lint` command to fix pipeline failures.

AUT-6131 Updated golangci-lint command

---

docker-compose.cdr.yaml

- updated `cdr-mock-data-recipient` docker image with fix - updated `ids` in query selector for View and Delete registered client action

AUT-6254 Set cdr-mock-data-recipient version to 0.0.10

---

.env-local
apps/developer-tpp/obuk_logic.go
data/imports/cdr.tmpl
docker-compose.cdr.yaml

Configure CDR workspace to use jwks uri for signing software statements instead of explicit key set
Related PR: https://github.com/cloudentity/mock-register/pull/2

Configure CDR workspace to use jwks uri for signing software statements instead of explicit key set

---

apps/financroo-tpp/http_transport.go
data/imports/cdr.tmpl

Turn on outgoing request debugging for financroo tpp. This applies to all autogenerated client requests, like those made to the mock bank application.

Financroo Outgoing Request Debug

---

Makefile
apps/financroo-tpp/clients.go
data/imports/cdr.tmpl
go.mod
go.sum

This PR modifies financroo to use private key jwt authentication for cdr flows. There is a related PR for the acp client go library located here: https://github.com/cloudentity/acp-client-go/pull/36

Financroo Private Key JWT Authentication for CDR

---

.env-local
.env-saas
Makefile
data/imports/cdr.tmpl
data/imports/fdx.tmpl
data/imports/openbanking-br.tmpl
data/imports/openbanking-uk.tmpl
data/variables.yaml
docker-compose.cdr.yaml
docker-compose.fdx.yaml
docker-compose.obbr.yaml
docker-compose.obuk.yaml
scripts/additional_configuration.sh
scripts/override_variables.sh

Configurable server id

---

Makefile
apps/financroo-tpp/clients.go
apps/financroo-tpp/config.go
apps/financroo-tpp/server.go
data/imports/cdr.tmpl
go.mod
go.sum

Disable automatic client credentials token endpoint calls being made by financroo for cdr. I've also merged in https://github.com/cloudentity/openbanking-quickstart/pull/197 which contains private key jwt updates for financroo

Disable Client Credentials for CDR Financroo TPP

---

docs/how_to_use_hypr.md

This PR updates the readme for HYPR doc by replacing the configuration file instructions with environment variables.

updated doc readme

---

README.md
consent/admin-portal/LICENSE
consent/consent-page/LICENSE
consent/self-service-portal/LICENSE

PI-37-update licenses

---

data/imports/fdx.tmpl

FDX enable hint for static IDP

FDX enable hint for static IDP

---

data/imports/openbanking-br.tmpl
data/imports/openbanking-uk.tmpl

rename Openbanking Brazil to Open Finance Brazil + Openbanking UK to Open Banking UK

AUT-6393 rename Openbanking Brazil to Open Finance Brazil

---

CODEOWNERS
go.mod
go.sum

Bump acp client

---

.env-local
data/imports/cdr.tmpl
docker-compose.acp.local.yaml
mount/redis/redis.conf

Bump Redis

---

data/imports/fdx.tmpl

Add UPDATE_CONSENTS to FDX client to enable it to use consent revocation API

Add UPDATE_CONSENTS to FDX client

---

apps/financroo-tpp/clients.go

Financroo for FDX was using ClientSecretPost authentication method but after merging AUT-6769 (FAPI based workspace) it will not work anymore so it is changed to mTLS.
Please add cypress tests to cover financroo scenarios for FDX.

AUT-6991 Modify Financroo for FDX to use mTLS

---

apps/financroo-tpp/web/app/src/components/BankCard.tsx
apps/financroo-tpp/web/app/src/components/Welcome.tsx
tests/cypress/integration/fdx/FdxFinancrooAccountsTests.ts
tests/cypress/integration/obbr/ConsentSelfServiceTests.ts
tests/cypress/integration/obbr/FinancrooPaymentsTests.ts
tests/cypress/integration/obuk/ConsentSelfServiceTests.ts
tests/cypress/integration/obuk/FinancrooAccountsTests.ts
tests/cypress/integration/obuk/FinancrooPaymentsTests.ts
tests/cypress/integration/saas/cdr/SmokeFinancrooAccountsTests.ts
tests/cypress/integration/saas/fdx/SmokeFdxFinancrooAccountsTests.ts
tests/cypress/integration/saas/obbr/SmokeConsentSelfServiceTests.ts
tests/cypress/integration/saas/obbr/SmokeFinancrooPaymentsTests.ts
tests/cypress/integration/saas/obuk/SmokeConsentSelfServiceTests.ts
tests/cypress/integration/saas/obuk/SmokeFinancrooAccountsTests.ts
tests/cypress/integration/saas/obuk/SmokeFinancrooPaymentsTests.ts
tests/cypress/pages/financroo/FinancrooWelcomePage.ts
tests/cypress/pages/financroo/accounts/FinancrooAccountsPage.ts
tests/cypress/pages/financroo/accounts/FinancrooModalPage.ts

Added Cypress tests scenarios for FDX Financroo for ACP deployed locally and on SaaS environment.
N/A

Add Cypress tests for Financroo

---

Makefile
apps/developer-tpp/fdx_logic.go
apps/developer-tpp/main.go
tests/cypress/pages/fdx-tpp/FdxTppAuthenticatedPage.ts

Added READ_CONSENTS and UPDATE_CONSENTS scopes to Developer TPP for FDX
Additionally fixed "make clean" for CDR to delete all containers

AUT-7029: Developer TPP client should request for READ_CONSENTS and UPDATE_CONSENTS scopes

---

Jenkinsfile
Makefile
data/imports/cdr.tmpl
data/variables.yaml
scripts/additional_configuration.sh
tests/cypress/integration/saas/cdr/SmokeFinancrooAccountsTests.ts

Enable SaaS tests for CDR

---

.env-local
apps/bank/fdx_get_accounts_handler.go
apps/bank/fdx_get_accounts_internal_handler.go
apps/bank/fdx_get_transactions_handler.go
apps/developer-tpp/fdx_logic.go
apps/developer-tpp/obbr_logic.go
apps/financroo-tpp/consent.go
consent/admin-portal/consent_logic.go
consent/admin-portal/main.go
consent/admin-portal/ob_cdr_logic.go
consent/admin-portal/ob_fdx_logic.go
consent/admin-portal/web/app/src/components/AccountView/AccountClientCard.tsx
consent/admin-portal/web/app/src/components/AccountView/ConsentTabs.tsx
consent/admin-portal/web/app/src/components/ClientCard.tsx
consent/admin-portal/web/app/src/components/utils.tsx
consent/consent-page/cdr_account_access_handler.go
consent/self-service-portal/cdr_arrangement_impl.go
consent/self-service-portal/fdx_bank_client.go
consent/self-service-portal/fdx_consent_impl.go
consent/self-service-portal/main.go
consent/self-service-portal/web/app/src/components/ApplicationSimpleCard.tsx
consent/self-service-portal/web/app/src/components/applicationDetails/ApplicationAccessTabs.tsx
docker-compose.cdr.yaml
docker-compose.fdx.yaml
go.mod
go.sum
tests/cypress/integration/cdr/CDRConsentAdminTests.ts
tests/cypress/integration/cdr/CDRConsentSelfServiceTests.ts
tests/cypress/pages/mock-data-recipient/DynamicClientRegistrationPage.ts
tests/cypress/pages/mock-data-recipient/PushedAuthorisationRequestPage.ts

Enable Admin Portal and Consent Self Service portal for FDX.

AUT-6741: Extend quickstart admin portal to support FDX

---

consent/self-service-portal/obbr_consent_impl.go
consent/self-service-portal/web/app/src/components/applicationDetails/ApplicationAccessTabs.tsx

Fix for bug where payment consents for open banking brasil were not showing up in the consent self service portal.

Add Payment Consent to Self Service Application for OBBR

---

apps/financroo-tpp/web/app/src/components/investments/InvestmentsContribute.tsx
apps/financroo-tpp/web/app/src/components/investments/InvestmentsContributeMethod.tsx

UI fixes in Financroo - passing wrong account id in payment fixed + not displaying account nickname in payment details fixed.

AUT-7243 financroo account details fix

---

consent/self-service-portal/fdx_bank_client.go
data/imports/fdx.tmpl
docker-compose.fdx.yaml
tests/cypress/integration/fdx/FdxFinancrooSelfServiceTests.ts
tests/cypress/integration/fdx/FdxTppConsentSelfServiceTests.ts
tests/cypress/integration/saas/fdx/SmokeFdxFinancrooSelfServiceTests.ts
tests/cypress/integration/saas/fdx/SmokeFdxTppSelfServiceTests.ts

Fix configuration for bank client used by the consent self service portal application for FDX.

Fix Bank Client for FDX Consent Self Service

---

Makefile
docker-compose.acp.local.yaml

Add jaeger tracing

---

Jenkinsfile
Makefile
apps/financroo-tpp/config_test.go
apps/financroo-tpp/connect_bank_routes.go
apps/financroo-tpp/consent_commons.go
apps/financroo-tpp/consent_commons_test.go
apps/financroo-tpp/payment_routes.go
apps/financroo-tpp/user_repo_test.go
consent/consent-page/obbr_account_access_handler.go
consent/consent-page/obuk_account_access_handler.go
consent/consent-page/otp_test.go
consent/self-service-portal/fdx_consent_impl.go

No changes visible to the users.
Added unit tests for CreateConsentResponse method.
Enabled unit tests in pipeline.
Fixed existing tests.

AUT-7083 Create unit tests to CreateConsentResponse method in openbanking-quickstart

---

tests/cypress/integration/saas/cdr/SmokeFinancrooConsentAdminTests.ts
tests/cypress/integration/saas/cdr/SmokeFinancrooConsentSelfServiceTests.ts
tests/cypress/integration/saas/fdx/SmokeFdxFinancrooConsentAdminTests.ts

This PR only uncomments tests that were failing becouse of this bug.
The bug was fixed on infrastructure by deploying RediSearch with RSCoordinator.

UAT-7237 Uncomment tests

---

tests/cypress/integration/saas/cdr/SmokeFinancrooConsentAdminTests.ts

Uncomment CDR tests

---

docker-compose.acp.local.yaml

Healthcheck added to CRDB container to fix starting order

AUT-8046: Add healthcheck to crdb container

---

Jenkinsfile
data/imports/cdr.tmpl
data/imports/fdx.tmpl
data/imports/openbanking-br.tmpl
data/imports/openbanking-uk.tmpl

Adjust clients response types to match allowed response types on the server.

Adjust clients response types

---

consent/self-service-portal/fdx_bank_client.go
data/imports/fdx.tmpl
docker-compose.fdx.yaml

FDX Internal Bank Client is now configured to use TLS client auth.
Consent self-service app is adjusted to take advantage from it.

AUT-8270: Use TLS client auth for  FDX Internal Bank Client

---

consent/self-service-portal/fdx_bank_client.go

Removing accidentally merged debug log

AUT-8270: Remove debug logging

---

docker-compose.acp.local.yaml
docker-compose.build.yaml
docker-compose.cdr.yaml
docker-compose.fdx.yaml
docker-compose.obbr.yaml
docker-compose.obuk.yaml

Define docker `platform` to resolve several issues with running the quickstart on Apple M1 processors.

Define docker platform to avoid issues with running the quickstart on M1

---

tests/cypress/pages/mock-data-recipient/ConsentAndAuthorisationCallbackPage.ts
tests/cypress/pages/mock-data-recipient/ConsentAndAuthorisationPage.ts
tests/cypress/pages/mock-data-recipient/DiscoverDataHoldersPage.ts
tests/cypress/pages/mock-data-recipient/DynamicClientRegistrationPage.ts
tests/cypress/pages/mock-data-recipient/PushedAuthorisationRequestPage.ts

Add clearLocalStorage to visit methods:
```
modified:   tests/cypress/pages/mock-data-recipient/ConsentAndAuthorisationCallbackPage.ts
modified:   tests/cypress/pages/mock-data-recipient/ConsentAndAuthorisationPage.ts
modified:   tests/cypress/pages/mock-data-recipient/DiscoverDataHoldersPage.ts
modified:   tests/cypress/pages/mock-data-recipient/DynamicClientRegistrationPage.ts
modified:   tests/cypress/pages/mock-data-recipient/PushedAuthorisationRequestPage.ts
```

[AUT-8778] Add clearLocalStorage to visit methods

---

Jenkinsfile
Makefile
scripts/format_xray_result.sh
scripts/retag_docker_images.sh

We are updating the Jenkins pipeline to include a new stage that will conduct nightly vulnerability scans using Artifactory Xray.

DEVOPS-2342 Add Xray scanning to the Openbanking Jenkins pipeline

---

.golangci.yml
Jenkinsfile
apps/bank/main.go
apps/bank/obbr_get_accounts_internal_handler.go
apps/bank/obbr_get_balances_internal_handler.go
apps/bank/obuk_create_payment_handler.go
apps/bank/obuk_get_accounts_handler.go
apps/bank/obuk_get_accounts_internal_handler.go
apps/bank/obuk_get_balances_handler.go
apps/bank/obuk_get_balances_internal_handler.go
apps/configuration/import.go
apps/configuration/import_test.go
apps/configuration/main.go
apps/custom-idp/handler.go
apps/developer-tpp/fdx_logic.go
apps/financroo-tpp/consent.go
apps/financroo-tpp/consent_commons_test.go
apps/financroo-tpp/user_secure_storage.go
build/runner.dockerfile
consent/consent-page/fdx_client.go
consent/consent-page/fdx_consent_tools.go
consent/consent-page/i18n.go
consent/consent-page/obbr_account_access_handler.go
consent/consent-page/obbr_bank_client.go
consent/consent-page/obuk_bank_client.go
consent/consent-page/sms_client.go
consent/self-service-portal/obbr_bank_client.go
consent/self-service-portal/obuk_bank_client.go
scripts/go/clean_saas.go

Re-enable golinter + code adjustments.

Re-enable golinter 

---

Jenkinsfile
Makefile
apps/bank/Dockerfile
apps/configuration/Dockerfile
apps/custom-idp/Dockerfile
apps/developer-tpp/Dockerfile
apps/financroo-tpp/Dockerfile
build/runner.dockerfile
consent/admin-portal/Dockerfile
consent/consent-page/Dockerfile
consent/self-service-portal/Dockerfile
docker-compose.cdr.yaml

- add a go proxy configuration to pull packages from `artifactory.cloudentity.com`

[DEVOPS-2682] GOPROXY configuration

---

.github/workflows/docker-publish.yml

Publish consent-storage docker to docker hub

[AUT-9867] Publish consent-storage docker to docker hub

---

.github/workflows/docker-publish.yml
docker-compose.generic.yaml

[AUT-9867] Fix consent storage image name

---

apps/configuration/import.go

Log trace id in configuration app in case of error for troubleshooting purposes.

[AUT-9869] Log trace id in configuration app in case of error

---

apps/bank/Dockerfile
apps/configuration/Dockerfile
apps/custom-idp/Dockerfile
apps/developer-tpp/Dockerfile
apps/financroo-tpp/Dockerfile
consent/admin-portal/Dockerfile
consent/consent-page/Dockerfile
consent/consent-storage/Dockerfile
consent/self-service-portal/Dockerfile

Upgrade to Alpine Edge to fix Vulnerabilities reported by Xray.
A new stable version of Alpine should replace it, once it's released

Upgrade Alpine

---

apps/bank/Dockerfile
apps/configuration/Dockerfile
apps/custom-idp/Dockerfile
apps/developer-tpp/Dockerfile
apps/financroo-tpp/Dockerfile
build/runner.dockerfile
consent/admin-portal/Dockerfile
consent/consent-page/Dockerfile
consent/consent-storage/Dockerfile
consent/self-service-portal/Dockerfile

Bump golang

---

apps/financroo-tpp/web/app/package-lock.json
consent/admin-portal/web/app/package-lock.json
consent/admin-portal/web/app/package.json
consent/self-service-portal/web/app/package-lock.json
consent/self-service-portal/web/app/package.json

bump npm deps to fix vulnerabilities raised by dependabot

AUT-10762 - bump npm deps

---

Jenkinsfile

Do not run OBBR tests as this spec it's no longer supported.

[AUT-10980] Do not run OBBR tests

---

.github/workflows/dependabot-auto-approve.yaml

Add dependabot auto approve
