data/imports/openbanking.tmpl, data/variables.yaml
If necessary it's now possible to override consent page client id and secret
=> Configurable consent page import credentials

docker-compose.yaml
This PR changes the docker-compose file to allow one to run quickstart alongside of the ACP repo `make prepare` without having to take down services due to conflicting names.
=> [AUT-4151]: Allow Quickstart to Run Beside ACP Repo

apps/custom-idp/.env, apps/custom-idp/docker-compose.yaml
A few docker-compose.yaml env vars were hardwired, instead of referring to the .env file values.
[AUT-5067]: https://cloudentity.atlassian.net/browse/AUT-5067?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AUT-5067 Fix docker-compose.yaml where env vars were hardwired.

consent/admin-portal/handler.go
Fix consent admin app to add `{workspaceID}` when querying clients using system API.
=> Fix consent admin request for clients

go.mod, go.sum
In this PR we update to include Dylan's latest updates to acp-client-go from
https://github.com/cloudentity/acp-client-go/pull/28
=> Update acp-client-go to include cloudentity/acp-client-go/pull/28

.env, .env-local, data/imports-cdr/cdr.tmpl, docker-compose.yaml
Set correct audience on CDR service and rename Redis docker to allow calling `make prepare` on ACP and running quickstart at the same time
=> Set correct audience on cdr service

consent/self-service-portal/handler.go, consent/self-service-portal/main.go, consent/self-service-portal/obbr_bank_client.go, consent/self-service-portal/obbr_consent_impl.go, consent/self-service-portal/obuk_bank_client.go, consent/self-service-portal/web/app/src/components/ApplicationSimpleCard.tsx, consent/self-service-portal/web/app/src/components/Dashboard.tsx, consent/self-service-portal/web/app/src/components/applicationDetails/ApplicationAccessTabs.tsx, consent/self-service-portal/web/app/src/components/applicationDetails/utils.tsx, docker-compose.yaml, tests/cypress/integration/obbr/ConsentSelfServiceTests.ts, tests/cypress/integration/obuk/ConsentSelfServiceTests.ts, tests/cypress/integration/obuk/FinancrooAccountsTests.ts, tests/cypress/integration/obuk/FinancrooPaymentsTests.ts, tests/cypress/pages/financroo/FinancrooWelcomePage.ts, tests/cypress/pages/financroo/accounts/FinancrooConnectAccountPage.ts
This PR adds open banking brasil support to the quickstart consent self service application. 
* Added consent retrieval using the ACP OBBR apis
* Added account retrieval using the internal /account api exposed by the mock bank application
* Added consent revocation using the ACP OBBR apis  
* Added cypress tests for retrieving an obbr consent in the self service portal and for revoking that consent
=> Open Banking Brasil Consent Self Service

data/imports/bank-customers.tmpl, data/imports/cdr.tmpl, data/imports/openbanking-br.tmpl, data/imports/openbanking-uk.tmpl
This PR adds hints to the static idp login pages so that users won't have to look elsewhere for login credentials when they are going through the app flows.
=> Add Hint To Static IDP Login Pages

consent/consent-page/cdr_client.go, consent/consent-page/main.go, docker-compose.cdr.yaml
This PR adds a new configuration option to completely override the accounts endpoint that the cdr consent page calls, instead of the prior behavior of calling `bankURL/internal/accounts`
This is controlled by a new environment variable in the cdr consent page service called `BANK_ACCOUNTS_ENDPOINT`
=> Override Internal Bank Accounts Endpoint for CDR Consent Page

.env-local, Makefile, docker-compose.cdr.yaml, scripts/bump_acp.sh
Bump acp and data recipient apps.
Data recipient corresponding PR: https://github.com/cloudentity/mock-data-recipient/pull/7
Add a simple script to bump acp docker image locally.
=> Bump acp and data recipient apps

Jenkinsfile, Makefile, scripts/go/clean_saas.go
Currently to execute  `clean_saas.go` the `obSpec` flag must be provided - this implementation depends on fixed list with workspace ID. 
Additionally with current solution, the clean up mechanism in the Jenkins plan is implemented at the end of the stage, not at the beginning (which is a bad solution in case of e.g.:  network connection failures).
TODO refactor:
- update `clean_saas.go` script to:
- remove `obSpec` flag
- GET the list of all available Servers 
- exclude the default servers such as: `System`, `Admin`, `Default` etc.
- remove non-default servers only 
- update `Jenkisfile` with `clean-saas` option implemented at the beginning of every SaaS Test stage
- update `Jenkisfile with `clean` option implemented at the beginning of every local Test stage
N/A
=> AUT-6324 - feature/AUT-6324-refactor-clean-saas-script

Jenkinsfile, build/runner.dockerfile
Recently openbanking-quickstart pipeline is failing due to:
```
#7 [3/9] RUN go install github.com/go-swagger/go-swagger/cmd/swagger@v0.26.1
#7 sha256:19c5274c5e235776abde46ed591ffaafd954005961c48b2b749514e8b38535a8
#7 12.37 go: github.com/go-swagger/go-swagger/cmd/swagger@v0.26.1: github.com/go-swagger/go-swagger/cmd/swagger@v0.26.1: Get "https://proxy.golang.org/github.com/go-swagger/go-swagger/cmd/swagger/@v/v0.26.1.info": 
#7 ERROR: executor failed running [/bin/sh -c go install github.com/go-swagger/go-swagger/cmd/swagger@v0.26.1]: exit code: 1
------
> [3/9] RUN go install github.com/go-swagger/go-swagger/cmd/swagger@v0.26.1:
------
executor failed running [/bin/sh -c go install github.com/go-swagger/go-swagger/cmd/swagger@v0.26.1]: exit code: 1
make: *** [Makefile:102: …
```
=> Added 20 minutes timeout

apps/developer-tpp/fdx_logic.go, apps/developer-tpp/main.go, apps/developer-tpp/templates/fdx/fdx-authenticated.tmpl, apps/financroo-tpp/fdx_client.go, data/imports/fdx.tmpl, tests/cypress/pages/fdx-tpp/FdxTppAuthenticatedPage.ts
Use MTLS instead of Client Secret  for TPP app for FDX
Additionally reduced the number of acpclient.Client to 1.
=> Use mTLS in FDX tpp app

Jenkinsfile
On Jenkins Ci there is a conflict between ACP and Openbanking Quickstart on port 8082. It looks like on Ci worker there are sometimes leftovers from ACP builds and port is already used which cause errors.
Solution: in Jenkinsfile remove all containers as a preparation step.
=> AUT-7148: Fix 8082 port conflict with ACP

scripts/additional_configuration.sh
Fix for 
```
./scripts/additional_configuration.sh: line 5: PREFIX=${3,,}: bad substitution
make: *** [run-obbr-local] Error 1
```
on mac os
=> Additional Configuration Script Fix for Mac

apps/financroo-tpp/consent.go, consent/consent-page/consent_tools.go, consent/consent-page/main.go, consent/consent-page/obbr_payments_handler.go, go.mod, go.sum, tests/cypress/integration/saas/cdr/SmokeFinancrooConsentAdminTests.ts, tests/cypress/integration/saas/cdr/SmokeFinancrooConsentSelfServiceTests.ts
Extended the consent page application to be compatible with retrieving v2 payment consents. This can be enabled by adding `OPENBANKING_BRASIL_PAYMENTS_VERSION=v2` to the consent page's environment.
=> Support for OBBR Payment Consents V2

consent/consent-page/consent_tools.go, consent/consent-page/obbr_payment_mfa_provider.go, consent/consent-page/obbr_payments_handler.go
The `debtorAccount` field in the obbr payment consent api is not mandatory, but the consent page will panic when trying to retrieve/approve a consent without it. 
I've adjusted the consent page to use a default value of `N/A` if that info isn't present in the consent in order to prevent the panic.
=> Fix Consent Page Panic When DebtorAccount Field is Absent

.env-local, data/imports/cdr.tmpl, docker-compose.acp.local.yaml
Bump crdb and acp
Temporary add RS256 as allowed signing alg fix for CDR. By default RS256 is not allowed for new CDR workspaces.
Enable CDR tests.
=> Bump crdb and acp + temporary enable RS256 for token endpoint signing alg

docker-compose.acp.local.yaml
Switch local redis to redis stack to solve problems with redisearch crashing on m1 apple cpus.
Analogically to https://github.com/cloudentity/acp/pull/4265 
Tested locally on obuk and all turned on properly
=> AUT-8041 -  switch redis search to redis stack

Jenkinsfile, Makefile
Timeout increased to make pipeline more stable. Probably in situation where we need to download new containers and CRDB starts slower the ACP container is restarted (+30s to startup time) and we reach standard 60s timeout. After the change startup time is increased to 120s.
=> AUT-8047: Increase COMPOSE_HTTP_TIMEOUT

docker-compose.acp.local.yaml
ACP cannot call data mock recipient as the certificate has expired.
As we are no longer actively maintaining this repository but still some people are using it mostly for demo purposes, I'm switching ACP http client to not verify certificate when calling external services.
```
{"error":"failed to get data recipients: Get \"https://mock-register:7000/cdr-register/v1/banking/data-recipients\": GET https://mock-register:7000/cdr-register/v1/banking/data-recipients giving up after 3 attempt(s): Get \"https://mock-register:7000/cdr-register/v1/banking/data-recipients\": tls: failed to verify certificate: x509: certificate has expired or is not yet valid: current time 2023-07-17T15:15:08Z is after 2023-06-15T05:36:38Z","level":"warning","msg":"failed to process cdr …
```
=> ACP skip certificate validation when calling external services
